extends Node

var ltrs = {
	"1": preload("res://assets/images/Letters/ru/1.png"),
	"2": preload("res://assets/images/Letters/ru/2.png"),
	"3": preload("res://assets/images/Letters/ru/3.png"),
	"4": preload("res://assets/images/Letters/ru/4.png"),
	"5": preload("res://assets/images/Letters/ru/5.png"),
	"6": preload("res://assets/images/Letters/ru/6.png"),
	"7": preload("res://assets/images/Letters/ru/7.png"),
	"8": preload("res://assets/images/Letters/ru/8.png"),
	"9": preload("res://assets/images/Letters/ru/9.png"),
	"10": preload("res://assets/images/Letters/ru/10.png"),
	"11": preload("res://assets/images/Letters/ru/11.png"),
	"12": preload("res://assets/images/Letters/ru/12.png"),
	"13": preload("res://assets/images/Letters/ru/13.png"),
	"14": preload("res://assets/images/Letters/ru/14.png"),
	"15": preload("res://assets/images/Letters/ru/15.png"),
	"16": preload("res://assets/images/Letters/ru/16.png"),
	"17": preload("res://assets/images/Letters/ru/17.png"),
	"18": preload("res://assets/images/Letters/ru/18.png"),
	"19": preload("res://assets/images/Letters/ru/19.png"),
	"20": preload("res://assets/images/Letters/ru/20.png"),
	"21": preload("res://assets/images/Letters/ru/21.png"),
	"22": preload("res://assets/images/Letters/ru/22.png"),
	"23": preload("res://assets/images/Letters/ru/23.png"),
	"24": preload("res://assets/images/Letters/ru/24.png"),
	"25": preload("res://assets/images/Letters/ru/25.png"),
	"26": preload("res://assets/images/Letters/ru/26.png"),
	"27": preload("res://assets/images/Letters/ru/27.png"),
	"28": preload("res://assets/images/Letters/ru/28.png"),
	"29": preload("res://assets/images/Letters/ru/29.png"),
	"30": preload("res://assets/images/Letters/ru/30.png"),
	"31": preload("res://assets/images/Letters/ru/31.png"),
	"32": preload("res://assets/images/Letters/ru/32.png"),
	"33": preload("res://assets/images/Letters/ru/33.png")
}

var en = {
	"1": preload("res://assets/images/Letters/en/1.png"),
	"2": preload("res://assets/images/Letters/en/2.png"),
	"3": preload("res://assets/images/Letters/en/3.png"),
	"4": preload("res://assets/images/Letters/en/4.png"),
	"5": preload("res://assets/images/Letters/en/5.png"),
	"6": preload("res://assets/images/Letters/en/6.png"),
	"7": preload("res://assets/images/Letters/en/7.png"),
	"8": preload("res://assets/images/Letters/en/8.png"),
	"9": preload("res://assets/images/Letters/en/9.png"),
	"10": preload("res://assets/images/Letters/en/10.png"),
	"11": preload("res://assets/images/Letters/en/11.png"),
	"12": preload("res://assets/images/Letters/en/12.png"),
	"13": preload("res://assets/images/Letters/en/13.png"),
	"14": preload("res://assets/images/Letters/en/14.png"),
	"15": preload("res://assets/images/Letters/en/15.png"),
	"16": preload("res://assets/images/Letters/en/16.png"),
	"17": preload("res://assets/images/Letters/en/17.png"),
	"18": preload("res://assets/images/Letters/en/18.png"),
	"19": preload("res://assets/images/Letters/en/19.png"),
	"20": preload("res://assets/images/Letters/en/20.png"),
	"21": preload("res://assets/images/Letters/en/21.png"),
	"22": preload("res://assets/images/Letters/en/22.png"),
	"23": preload("res://assets/images/Letters/en/23.png"),
	"24": preload("res://assets/images/Letters/en/24.png"),
	"25": preload("res://assets/images/Letters/en/25.png"),
	"26": preload("res://assets/images/Letters/en/26.png"),
}

var nums = {
	"1": preload("res://assets/images/Numbers/1.png"),
	"2": preload("res://assets/images/Numbers/2.png"),
	"3": preload("res://assets/images/Numbers/3.png"),
	"4": preload("res://assets/images/Numbers/4.png"),
	"5": preload("res://assets/images/Numbers/5.png"),
	"6": preload("res://assets/images/Numbers/6.png"),
	"7": preload("res://assets/images/Numbers/7.png"),
	"8": preload("res://assets/images/Numbers/8.png"),
	"9": preload("res://assets/images/Numbers/9.png"),
	"10": preload("res://assets/images/Numbers/10.png"),
	"11": preload("res://assets/images/Numbers/11.png"),
	"12": preload("res://assets/images/Numbers/12.png")
}

var diff = {
	"100": preload("res://assets/bonuses/rock.png")
}
